version: '3.8'
services:
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_NAME: mydatabase
    ports:
      - "3001:3000"

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
